version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/.github/workflows"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "github-actions"
    labels:
      - "CI/CD"
      - "dependencies"
    groups:
      github-actions-minor-patch:
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 20
    commit-message:
      prefix: "npm"
    labels:
      - "npm"
      - "dependencies"
    groups:
      npm-minor-patch:
        update-types:
          - "minor"
          - "patch"
