name: 不具合の報告
description: 不具合を報告するためのテンプレートです。
title: "[Bug]: "
labels: ["bug", "not triaged"]
body:
  - type: markdown
    attributes:
      value: |
        不具合の報告にご協力いただきありがとうございます！
        報告したい不具合が機密情報を含むセキュリティ関連の問題、脆弱性である場合、 [Open a draft security advisory](../security/advisories/new) から報告するようお願いします。
  - type: textarea
    id: expected-behavior
    attributes:
      label: 期待する動作
      description: 本来あるべき状態や動作を詳細に説明してください。
    validations:
      required: true
  - type: textarea
    id: current-behavior
    attributes:
      label: 現在の動作
      description: 現在の状態や動作を説明してください。
    validations:
      required: true
  - type: textarea
    id: possible-solution
    attributes:
      label: 考えられる解決策
      description: どのようにすれば不具合を解決できるか、案を記載してください。不明な場合は未記載で構いません。
  - type: textarea
    id: repro-steps
    attributes:
      label: 再現手順
      description: 不具合の再現手順や入力値を記載してください。再現手順が不明な場合は未記載で構いません。
      value: |
        1.
        2.
        3.
  - type: textarea
    id: environment
    attributes:
      label: 環境
      description: 不具合の発生する環境やバージョンについて、詳細に記述してください。
      value: |
        - OS / バージョン : Windows xx / Linux (distribution) / macOS xx
        - ブラウザー / バージョン : Chrome xx.xx / Edge xx.xx / FireFox xx.xx / Safari xx.xx
        - dotnet バージョン : dotnet x.x.x
        - その他 : ビルド環境などできる限り詳細な情報
  - type: textarea
    id: logs
    attributes:
      label: ログ・スタックトレース
      description: スタックトレースなど、アプリケーションやビルドシステムの出力するログを添付してください。
  - type: checkboxes
    id: confirmation
    attributes:
      label: 確認
      description: 以下の項目の確認および同意ができたら、チェックボックスをオンにしてください。
      options:
        - label: 報告しようとしている不具合がセキュリティ関連の問題、脆弱性に関するものではないことを確認しました。セキュリティ関連の問題、脆弱性の場合は [Open a draft security advisory](../security/advisories/new) から報告してください。
          required: true
        - label: 報告しようとしている不具合が [Issues](../issues) および [Discussions](../discussions) に登録されていないことを確認しました。
          required: true
        - label: 私たちの [行動規範](../?tab=coc-ov-file) に従うことを同意します。
          required: true